# Generated by Django 3.2.5 on 2022-03-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entered_invite_code',
            field=models.CharField(max_length=11, null=True, verbose_name='entered invite code'),
        ),
    ]
