# Generated by Django 3.2.5 on 2022-03-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registrations', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='your_invitees',
            field=models.CharField(max_length=500, null=True, verbose_name='your invitees'),
        ),
    ]
