# Generated by Django 3.2.5 on 2022-03-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('surname', models.CharField(max_length=500, verbose_name='surname')),
                ('invite_code', models.CharField(max_length=11, null=True, verbose_name='invite code')),
            ],
        ),
    ]
